import React from 'react';
import { act, fireEvent, render, screen, within } from '@testing-library/react-native';
import { StyleSheet } from 'react-native';
import App, { profileLibrary } from '../App';

jest.mock('@expo/vector-icons/Ionicons', () => {
  const React = require('react'); const { Text } = require('react-native');
  return { __esModule: true, default: ({ name, ...props }) => <Text {...props}>{name}</Text> };
});
jest.mock('@react-native-community/datetimepicker', () => {
  const React = require('react'); const { Pressable, Text } = require('react-native');
  return { __esModule: true, default: ({ mode, value, onChange, accessibilityLabel }) => <Pressable accessibilityLabel={accessibilityLabel || `${mode} picker open`} onPress={() => onChange({}, new Date(value.getTime() + 3600000))}><Text>{mode} picker</Text></Pressable> };
});

const openTab = label => fireEvent.press(screen.getByLabelText(`${label} tab`));
const openDiscover = () => openTab('Discover');
const openConnection = () => fireEvent.press(screen.getByLabelText('Open Haley and Ari Connection'));
const swipeNext = () => fireEvent.press(screen.getByLabelText('Next profile'));
const expireBanner = () => act(() => jest.advanceTimersByTime(4100));

describe('Bonus Human final prototype flows', () => {
  afterEach(() => jest.useRealTimers());
  test('uses five tabs and state-aware landing', () => { render(<App />); ['Discover', 'Connections', 'Pets', 'Feed', 'Account'].forEach(x => expect(screen.getByLabelText(`${x} tab`)).toBeTruthy()); expect(screen.getByText('People you’re building with')).toBeTruthy(); });
  test('Discover filters retain staged controls and close through Done', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Distance · 10 mi filter')); expect(screen.getByText('Reset')).toBeTruthy(); expect(screen.queryByLabelText('Cancel filter changes')).toBeNull(); fireEvent.press(screen.getByText('Done')); expect(screen.queryByText('How nearby?')).toBeNull(); fireEvent.press(screen.getByLabelText('Schedule filter')); expect(screen.getByLabelText('Select all PM')).toBeTruthy(); expect(screen.getByText('Weekends')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Monday PM')); fireEvent.press(screen.getByLabelText('Dismiss filters')); expect(screen.getByLabelText('Schedule filter')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Visit type filter')); expect(screen.getByText('House sitting')).toBeTruthy(); fireEvent.press(screen.getByText('Done')); fireEvent.press(screen.getByLabelText('Home filter')); expect(screen.getByLabelText('Dogs No dogs')).toBeTruthy(); expect(screen.queryByText('Has cats')).toBeNull(); });
  test('expanded profile data still respects AND filtering', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Schedule filter')); fireEvent.press(screen.getByLabelText('Monday AM')); fireEvent.press(screen.getByText('Done')); fireEvent.press(screen.getByLabelText('Experience filter')); fireEvent.press(screen.getByLabelText('Puppy care')); fireEvent.press(screen.getByText('Done')); fireEvent.press(screen.getByLabelText('Home filter')); fireEvent.press(screen.getByLabelText('Home type Apartment')); fireEvent.press(screen.getByText('Done')); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Alex')).toBeTruthy(); expect(screen.queryByLabelText('Open Haley & Ari profile')).toBeNull(); });
  test('Discover card opens on tap', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Open Haley & Ari profile')); expect(screen.getByText('The practical fit')).toBeTruthy(); });
  test('swipe navigation changes profile without opening it or making a decision', () => { render(<App />); openDiscover(); swipeNext(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Jordan')).toBeTruthy(); expect(screen.queryByText('The practical fit')).toBeNull(); expect(screen.queryByText('Request sent')).toBeNull(); });
  test('committed swipe reuses the already-rendered destination gallery', () => { render(<App />); openDiscover(); const readyGallery = screen.getByLabelText('Jordan gallery'); expect(screen.getByLabelText('Next profile ready')).toBeTruthy(); swipeNext(); const activeCard = screen.getByLabelText('Discover swipe card'); expect(within(activeCard).getByText('Jordan')).toBeTruthy(); expect(within(activeCard).getByLabelText('Jordan gallery')).toBe(readyGallery); expect(within(activeCard).queryByText('Haley & Ari')).toBeNull(); expect(screen.getByLabelText('Previous profile ready')).toBeTruthy(); });
  test('swiping past the first profile snaps back', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Previous profile')); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Haley & Ari')).toBeTruthy(); swipeNext(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Jordan')).toBeTruthy(); });
  test('Discover removes visible Previous/Next and filter-row arrow', () => { render(<App />); openDiscover(); expect(screen.queryByText('← Previous')).toBeNull(); expect(screen.queryByText('Next →')).toBeNull(); expect(screen.queryByText('chevron-forward')).toBeNull(); });
  test('Request sent banner appears after the card advances and remains temporarily actionable', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Connect')); expect(screen.getByText('Request sent')).toBeTruthy(); expect(screen.getByLabelText('Undo request')).toBeTruthy(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Jordan')).toBeTruthy(); expireBanner(); expect(screen.queryByLabelText('Discover confirmation banner')).toBeNull(); });
  test('Undo from the request banner restores the profile to Discover', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Connect')); fireEvent.press(screen.getByLabelText('Undo request')); expect(screen.queryByLabelText('Discover confirmation banner')).toBeNull(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Haley & Ari')).toBeTruthy(); });
  test('Not now advances immediately and remains reversible from its banner', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByText('Not now')); expect(screen.getByLabelText('Undo pass')).toBeTruthy(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Jordan')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Undo pass')); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Haley & Ari')).toBeTruthy(); });
  test('Jordan mutual banner opens the Jordan Connection, never the Haley and Ari Connection', () => { jest.useFakeTimers(); render(<App />); openDiscover(); swipeNext(); fireEvent.press(screen.getByLabelText('Connect')); expect(screen.getByText("You're connected")).toBeTruthy(); expect(screen.getByLabelText('Open Jordan Connection')).toBeTruthy(); expect(screen.queryByLabelText('Open Jordan profile')).toBeNull(); fireEvent.press(screen.getByLabelText('Open Jordan Connection')); expect(screen.getAllByText('Jordan').length).toBeGreaterThan(0); expect(screen.queryByText('Haley & Ari')).toBeNull(); fireEvent.press(screen.getByLabelText('Go back')); expect(screen.getByLabelText('Discover tab')).toBeTruthy(); });
  test('Requests management can restore a sent request to Discover', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Connect')); openTab('Connections'); fireEvent.press(screen.getByLabelText('Requests tab')); expect(screen.getByText('WANTS TO CONNECT')).toBeTruthy(); expect(screen.getByText('REQUEST SENT')).toBeTruthy(); fireEvent.press(screen.getByText('Undo request')); openDiscover(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Haley & Ari')).toBeTruthy(); });
  test('Passed management can reconsider a profile back into Discover', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByText('Not now')); openTab('Connections'); fireEvent.press(screen.getByLabelText('Passed tab')); fireEvent.press(screen.getByText('Reconsider pass')); openDiscover(); expect(within(screen.getByLabelText('Discover swipe card')).getByText('Haley & Ari')).toBeTruthy(); });
  test('group profile exposes joint, Haley, and Ari tabs', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Open Haley & Ari profile')); expect(screen.getByLabelText('Haley & Ari Discover profile tab')).toBeTruthy(); expect(screen.getByLabelText('Haley Discover profile tab')).toBeTruthy(); expect(screen.getByLabelText('Ari Discover profile tab')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Ari Discover profile tab')); expect(screen.getByText(/senior-rescue volunteer/)).toBeTruthy(); });
  test('Discover profile context alone exposes Previous and Next browsing', () => { render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Open Haley & Ari profile')); expect(screen.getByText('← Previous')).toBeTruthy(); expect(screen.getByText('Next →')).toBeTruthy(); });
  test('Connection profile navigation stays scoped to participants', () => { render(<App />); openConnection(); fireEvent.press(screen.getByLabelText('Open Haley and Ari profile')); expect(screen.queryByText('Next →')).toBeNull(); expect(screen.queryByText('Jordan')).toBeNull(); fireEvent.press(screen.getByLabelText('Go back')); expect(screen.getByLabelText('Overview Connection tab')).toBeTruthy(); });
  test('profile opened from Requests cannot browse unrelated profiles', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Connect')); openTab('Connections'); fireEvent.press(screen.getByLabelText('Requests tab')); fireEvent.press(screen.getByLabelText('Open Haley & Ari profile')); expect(screen.queryByText('← Previous')).toBeNull(); expect(screen.queryByText('Next →')).toBeNull(); expect(screen.queryByText('Jordan')).toBeNull(); });
  test('Haley and Ari Connection title excludes Zuki while keeping Zuki in participants', () => { render(<App />); openConnection(); expect(screen.getAllByText('Haley & Ari').length).toBeGreaterThan(0); expect(screen.queryByText('Haley & Ari + Zuki')).toBeNull(); expect(screen.getByText('Zuki')).toBeTruthy(); });
  test('owner tabs are dynamic and Mochi has a photo', () => { render(<App />); openTab('Account'); fireEvent.press(screen.getByLabelText('Switch mode')); fireEvent.press(screen.getByText('Bonus Human')); openDiscover(); swipeNext(); fireEvent.press(screen.getByLabelText('Open Priya + Mochi profile')); expect(screen.getByLabelText('Priya Discover profile tab')).toBeTruthy(); expect(screen.getByLabelText('Mochi Discover profile tab')).toBeTruthy(); expect(screen.queryByLabelText('Mike Discover profile tab')).toBeNull(); fireEvent.press(screen.getByLabelText('Mochi Discover profile tab')); expect(screen.getByText('Life with Mochi')).toBeTruthy(); expect(screen.getByLabelText('Next photo')).toBeTruthy(); expect(screen.getByText('5 years old · Terrier mix')).toBeTruthy(); });
  test('Zuki summary opens the canonical pet profile', () => { render(<App />); openTab('Account'); fireEvent.press(screen.getByLabelText('Switch mode')); fireEvent.press(screen.getByText('Bonus Human')); openDiscover(); fireEvent.press(screen.getByLabelText('Open Mike + Zuki profile')); fireEvent.press(screen.getByLabelText('Zuki Discover profile tab')); fireEvent.press(screen.getByText('Open Zuki’s full profile')); expect(screen.getByLabelText('Profile pet tab')).toBeTruthy(); expect(screen.getByLabelText('Care Guide pet tab')).toBeTruthy(); expect(screen.getByLabelText('Open Zuki emergency information')).toBeTruthy(); });
  test('canonical pet profile keeps a true floating Emergency action and care access', () => { render(<App />); openTab('Pets'); fireEvent.press(screen.getByLabelText('Open Zuki Profile')); const dock = screen.getByLabelText('Floating Emergency action'); const dockStyle = StyleSheet.flatten(dock.props.style); expect(dockStyle.position).toBe('absolute'); expect(dockStyle.right).toBe(16); expect(dockStyle.backgroundColor).toBeUndefined(); expect(dockStyle.borderTopWidth).toBeUndefined(); expect(screen.getByLabelText('Open Zuki emergency information')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Care Guide pet tab')); expect(screen.getByLabelText('Heart medicine')).toBeTruthy(); });
  test('final stage is Bonus Human with consistent back/forward controls', () => { render(<App />); openConnection(); expect(screen.getByText('Skip this step →')).toBeTruthy(); fireEvent.press(screen.getByText('Skip this step →')); expect(screen.getByText('← Back to Meet & Greet')).toBeTruthy(); expect(screen.getByText('Move to Bonus Human →')).toBeTruthy(); fireEvent.press(screen.getByText('Move to Bonus Human →')); expect(screen.getAllByText('Bonus Human').length).toBeGreaterThan(0); expect(screen.queryByText(/Regular Bonus Human/)).toBeNull(); });
  test('shared scheduling sheet always exposes date, start, and end fields', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); ['Visit date', 'Start time', 'End time'].forEach(label => expect(screen.getByLabelText(label)).toBeTruthy()); fireEvent.press(screen.getByText('Cancel')); fireEvent.press(screen.getByText('Skip this step →')); fireEvent.press(screen.getByText('Schedule Trial Visit')); ['Visit date', 'Start time', 'End time'].forEach(label => expect(screen.getByLabelText(label)).toBeTruthy()); });
  test('date and time fields render one native control without duplicates', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); ['Visit date', 'Start time', 'End time'].forEach(label => expect(screen.getAllByLabelText(label)).toHaveLength(1)); });
  test('multiple visit requests remain independent in schedule summary', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); fireEvent.press(screen.getByText('Send request')); fireEvent.press(screen.getByText('Schedule Meet & Greet')); fireEvent.press(screen.getByText('Send request')); expect(screen.getAllByText('requested')).toHaveLength(2); expect(screen.getByText('Time together, at a glance')).toBeTruthy(); fireEvent.press(screen.getAllByText('Confirm as Mike')[0]); expect(screen.getByText('confirmed')).toBeTruthy(); expect(screen.getByText('requested')).toBeTruthy(); });
  test('one-off visit can be edited and keeps its changed time', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); fireEvent.press(screen.getByText('Send request')); fireEvent.press(screen.getByText('Edit / reschedule')); expect(screen.getByText('Edit one-off visit')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Start time')); fireEvent.press(screen.getByText('Save new time')); expect(screen.getByText(/1:00 PM–4:00 PM/)).toBeTruthy(); });
  test('one-off visit can be deleted from the schedule', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); fireEvent.press(screen.getByText('Send request')); expect(screen.getByText('UPCOMING VISITS')).toBeTruthy(); fireEvent.press(screen.getByText('Cancel visit')); expect(screen.queryByText('UPCOMING VISITS')).toBeNull(); expect(screen.queryByText('Cancel visit')).toBeNull(); });
  test('scheduling activity includes date and time', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Schedule Meet & Greet')); fireEvent.press(screen.getByText('Send request')); fireEvent.press(screen.getByLabelText('Chat Connection tab')); expect(screen.getByText(/Haley & Ari requested a Meet & Greet: .* · .*–.*\./)).toBeTruthy(); });
  test('recurring schedules sort and abbreviate days and remain visually distinct', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Skip this step →')); fireEvent.press(screen.getByText('Move to Bonus Human →')); fireEvent.press(screen.getByText('Manage recurring schedule')); fireEvent.press(screen.getByLabelText('Recurring Wednesday')); fireEvent.press(screen.getByLabelText('Recurring Tuesday')); fireEvent.press(screen.getByText('Add recurring window')); expect(screen.getAllByText(/Recurring · Tue, Wed, Thu/).length).toBeGreaterThan(0); expect(screen.getAllByText('RECURRING SCHEDULE').length).toBeGreaterThan(0); expect(screen.queryByText(/Tuesday, Wednesday, Thursday/)).toBeNull(); fireEvent.press(screen.getByText('Add recurring window')); expect(screen.getAllByText('Edit window')).toHaveLength(2); fireEvent.press(screen.getAllByText('Edit window')[0]); expect(screen.getByText('Save recurring window')).toBeTruthy(); fireEvent.press(screen.getAllByText('Delete window')[0]); expect(screen.getAllByText('Edit window')).toHaveLength(1); });
  test('recurring editor opens focused and closes when leaving Bonus Human', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Skip this step →')); fireEvent.press(screen.getByText('Move to Bonus Human →')); fireEvent.press(screen.getByText('Manage recurring schedule')); expect(screen.getByText('Plan regular time together')).toBeTruthy(); fireEvent.press(screen.getByText('← Back to Trial Visits')); expect(screen.queryByText('Plan regular time together')).toBeNull(); expect(screen.getByText('Move to Bonus Human →')).toBeTruthy(); });
  test('stage controls are subtle underlined links in one row and navigate both directions', () => { render(<App />); openConnection(); fireEvent.press(screen.getByText('Skip this step →')); const controls = screen.getByLabelText('Connection stage controls'); const back = within(controls).getByText('← Back to Meet & Greet'); const forward = within(controls).getByText('Move to Bonus Human →'); expect(StyleSheet.flatten(back.props.style).textDecorationLine).toBe('underline'); expect(StyleSheet.flatten(forward.props.style).textDecorationLine).toBe('underline'); fireEvent.press(back); expect(screen.getByText('Skip this step →')).toBeTruthy(); });
  test('connection-request vocabulary avoids legacy interest terms', () => { jest.useFakeTimers(); render(<App />); openDiscover(); fireEvent.press(screen.getByLabelText('Connect')); expect(screen.getByText('Request sent')).toBeTruthy(); openTab('Connections'); fireEvent.press(screen.getByLabelText('Requests tab')); expect(screen.queryByText(/Interest sent|Interested profiles|Undo interested/)).toBeNull(); });
  test('mock profile library has 30 unique profiles split evenly across roles', () => { expect(profileLibrary).toHaveLength(30); expect(new Set(profileLibrary.map(profile => profile.id)).size).toBe(30); expect(profileLibrary.filter(profile => profile.role === 'owner')).toHaveLength(15); expect(profileLibrary.filter(profile => profile.role === 'bonus')).toHaveLength(15); });
  test('End Connection remains reachable through settings', () => { render(<App />); openConnection(); expect(screen.queryByText('End Connection')).toBeNull(); fireEvent.press(screen.getByLabelText('Connection settings')); expect(screen.getByText('End Connection')).toBeTruthy(); fireEvent.press(screen.getByText('End Connection')); expect(screen.getByText('Are you sure?')).toBeTruthy(); });
  test('double-tapping a human chat message toggles heart', () => { render(<App />); openConnection(); fireEvent.press(screen.getByLabelText('Chat Connection tab')); const message = screen.getByLabelText('Message from Haley & Ari'); fireEvent.press(message); fireEvent.press(message); expect(screen.getByText('♥')).toBeTruthy(); fireEvent.press(message); fireEvent.press(message); expect(screen.queryByText('♥')).toBeNull(); });
  test('Feed defaults to collapsed filters and composer', () => { render(<App />); openTab('Feed'); expect(screen.getByLabelText('Open Feed filters')).toBeTruthy(); expect(screen.getByLabelText('Share an update')).toBeTruthy(); expect(screen.queryByLabelText('Feed post text')).toBeNull(); expect(screen.queryByText('Post update')).toBeNull(); });
  test('Feed filters open in a sheet and show active count', () => { render(<App />); openTab('Feed'); fireEvent.press(screen.getByLabelText('Open Feed filters')); fireEvent.press(screen.getByLabelText('Feed author Mike')); fireEvent.press(screen.getByText('Done')); expect(screen.getByText('Filters · 1')).toBeTruthy(); expect(screen.queryByText('Sweet sixteen. Zuki tolerated her birthday hat for about four seconds.')).toBeNull(); });
  test('Feed composer progressively reveals controls and creates post', () => { render(<App />); openTab('Feed'); fireEvent.press(screen.getByLabelText('Share an update')); fireEvent.changeText(screen.getByLabelText('Feed post text'), 'Zuki enjoyed a sunny nap.'); fireEvent.press(screen.getByLabelText('Post type Milestone')); fireEvent.press(screen.getByText('Post update')); expect(screen.getByText('Zuki enjoyed a sunny nap.')).toBeTruthy(); });
  test('Feed edits inline', () => { render(<App />); openTab('Feed'); fireEvent.press(screen.getByLabelText('Edit post We went for a short, very sniff-focused walk.')); expect(screen.getByLabelText('Edit Feed post text')).toBeTruthy(); fireEvent.changeText(screen.getByLabelText('Edit Feed post text'), 'Zuki took a slow sunset walk.'); fireEvent.press(screen.getByText('Save post')); expect(screen.getByText('Zuki took a slow sunset walk.')).toBeTruthy(); });
  test('Feed Remove leaves a restorable placeholder', () => { render(<App />); openTab('Feed'); fireEvent.press(screen.getByLabelText('Remove post We went for a short, very sniff-focused walk.')); expect(screen.getByText('This update was removed.')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Restore post We went for a short, very sniff-focused walk.')); expect(screen.getByText('We went for a short, very sniff-focused walk.')).toBeTruthy(); });
  test('Account prototype controls still work', () => { render(<App />); openTab('Account'); fireEvent.press(screen.getByLabelText('Edit profile completeness')); expect(screen.getByText('Lead with who you are')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Go back')); fireEvent.press(screen.getByLabelText('Help')); expect(screen.getByText('Help Center is not in this prototype')).toBeTruthy(); });
});
